global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'task_manager'

scrape_configs:
  - job_name: 'app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['db-exporter:9187']
        labels:
          job: 'postgresql'
          service: 'task_manager'
          env: '${APP_ENV:-development}'

  - job_name: 'pyroscope'
    static_configs:
      - targets: ['pyroscope:4040']
        labels:
          component: 'profiler'
