definitions:
  usecases.AuthCommandExchangeOtpInput:
    properties:
      email:
        example: murat@murat.murat
        type: string
      otp:
        example: ""
        type: string
    required:
    - email
    - otp
    type: object
  usecases.AuthCommandExchangeOtpOutput:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  usecases.AuthCommandRefreshInput:
    properties:
      refreshToken:
        example: ""
        type: string
    required:
    - refreshToken
    type: object
  usecases.AuthCommandRefreshOutput:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  usecases.AuthCommandSignInInput:
    properties:
      email:
        example: murat@murat.murat
        type: string
    required:
    - email
    type: object
  usecases.AuthCommandSignInOutput:
    properties:
      message:
        type: string
    type: object
  usecases.AuthQueryMeOutput:
    properties:
      message:
        description: Claims *components.JWTClaims
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Taskman API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Taskman API
  version: "1.0"
paths:
  /api/auth/exchange-otp:
    post:
      consumes:
      - application/json
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.AuthCommandExchangeOtpInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.AuthCommandExchangeOtpOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/usecases.AuthCommandExchangeOtpOutput'
      summary: Exchange OTP
      tags:
      - Auth
  /api/auth/me:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.AuthQueryMeOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/usecases.AuthQueryMeOutput'
      security:
      - ApiKeyAuth: []
      summary: Me
      tags:
      - Auth
  /api/auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.AuthCommandRefreshInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.AuthCommandRefreshOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/usecases.AuthCommandRefreshOutput'
      summary: Refresh
      tags:
      - Auth
  /api/auth/sign-in:
    post:
      consumes:
      - application/json
      parameters:
      - description: input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/usecases.AuthCommandSignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/usecases.AuthCommandSignInOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/usecases.AuthCommandSignInOutput'
      summary: Sign in
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    description: Type "Bearer" followed by a space and JWT token. <-- description
      (optional)
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
