services:
#  prometheus:
#    image: prom/prometheus:latest
#    restart: unless-stopped
#    volumes:
#      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
#      - ../prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
#      - prometheus_data:/prometheus
#    ports:
#      - "127.0.0.1:${DOCKER_PORT_PROMETHEUS:?}:9090"
#    command:
#      - --config.file=/etc/prometheus/prometheus.yml
#      - --storage.tsdb.path=/prometheus
#      - --storage.tsdb.retention.time=30d
#      - --web.enable-lifecycle
#      - --web.enable-remote-write-receiver
#      - --enable-feature=exemplar-storage
#      - --enable-feature=native-histograms
#    healthcheck:
#      test: wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1
#      interval: 15s
#      timeout: 5s
#      retries: 3


#  grafana:
#    image: grafana/grafana:latest
#    restart: unless-stopped
#    volumes:
#      - grafana_data:/var/lib/grafana
#      - ../grafana/provisioning:/etc/grafana/provisioning
#      - ../grafana/dashboards:/etc/grafana/dashboards
#    ports:
#      - "127.0.0.1:${DOCKER_PORT_GRAFANA:?}:3000"
#    depends_on:
#      - prometheus
#    environment:
#      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:?}
#      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "grafana-clock-panel"
#      #      GF_INSTALL_PLUGINS: grafana-pyroscope-datasource,grafana-tempo-datasource
#      GF_FEATURE_TOGGLES_ENABLE: traceqlEditor
#
#      GF_DEFAULT_INSTANCE_NAME: "Task Manager"
#      GF_SERVER_DOMAIN: "localhost"
#      GF_SERVER_ROOT_URL: "http://localhost:3000"
#    healthcheck:
#      test: wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1
#      interval: 15s
#      timeout: 5s
#      retries: 3

#  jaeger:
#    image: jaegertracing/all-in-one
#    environment:
#      - COLLECTOR_OTLP_ENABLED=true
#    ports:
#      - "16686:16686"  # UI
#      - "4317:4317"    # OTLP gRPC
#      - "4318:4318"    # OTLP HTTP
#    command:
#      - "--collector.otlp.enabled=true"

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"

volumes:
  grafana_data:
  prometheus_data:
