apiVersion: 1

datasources:
  - name: Pyroscope
    type: grafana-pyroscope-datasource
#    uid: pyroscope
    access: proxy
    url: http://pyroscope:4040
    editable: false
    jsonData:
      minStep: 15s
      backendType: phlare
      keepAlive: '30s'
    version: 1
